services:
  redis:
    image: redis
    container_name: redis
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   redis-data:

networks:
    core_docker_network:
      external: true

