services:
  redis:
    image: redis:8.4.0
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    # hostname: "0.0.0.0"
    command: >
      sh -c 'redis-server --requirepass "$$REDIS_PASSWORD" --bind 0.0.0.0 --protected-mode yes'
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   redis-data:

networks:
    core_docker_network:
      external: true

