services:
  couchbase:
    image: couchbase
    container_name: couchbase
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "8091:8091"
    volumes:
      - ./data:/opt/couchbase/var
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   couchbase-data:

networks:
    core_docker_network:
      external: true

