services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana # chown -R 472:472 path/dir (472 official grafana)
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   grafana-data:

networks:
    core_docker_network:
      external: true

